# Generated by Django 3.1.7 on 2021-03-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextData',
            new_name='keyword',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='keyword',
            new_name='keyword_val',
        ),
    ]
