# Generated by Django 3.1.7 on 2021-03-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210309_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='keyword_val',
            new_name='keyword_values',
        ),
    ]
