# Generated by Django 3.1.7 on 2021-03-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_about_us'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_Us',
            new_name='About_U',
        ),
    ]
