# Generated by Django 3.1.7 on 2021-03-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210309_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_values', models.CharField(max_length=100, verbose_name='Keyword')),
                ('intent', models.CharField(max_length=1000, verbose_name='Intent')),
            ],
        ),
        migrations.DeleteModel(
            name='keyword',
        ),
    ]
