# Generated by Django 3.1.7 on 2021-03-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210309_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='text_keyword',
            options={'verbose_name': 'Text Keyword and Intent', 'verbose_name_plural': 'Text Keywords and Intents'},
        ),
    ]
