# Generated by Django 3.1.7 on 2021-03-11 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210310_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text_keyword',
            options={'verbose_name': 'Text Keyword and link', 'verbose_name_plural': 'Text Keywords and Links'},
        ),
    ]
