# Generated by Django 3.1.7 on 2021-03-11 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210311_0443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='link_keyword',
            options={'verbose_name': 'text keyword and link', 'verbose_name_plural': 'Text Keywords and Links'},
        ),
        migrations.RenameField(
            model_name='link_keyword',
            old_name='intent',
            new_name='links',
        ),
    ]
