# Generated by Django 3.1.7 on 2021-03-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210311_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_keyword',
            name='links',
            field=models.CharField(max_length=1000, verbose_name='Link'),
        ),
    ]
