# Generated by Django 3.1.7 on 2021-03-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210311_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_value', models.CharField(max_length=100, verbose_name='Keyword')),
                ('desc', models.TextField(verbose_name='Intent')),
            ],
            options={
                'verbose_name': 'text keyword and link',
                'verbose_name_plural': 'Text Keywords and Links',
            },
        ),
    ]
