# Generated by Django 3.1.7 on 2021-03-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_text_keyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text_keyword',
            options={'verbose_name': 'text keyword and intent', 'verbose_name_plural': 'Text Keywords and Intents'},
        ),
    ]
