# Generated by Django 3.1.7 on 2021-03-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20210311_0520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link_keyword',
            options={'verbose_name': 'keyword and link', 'verbose_name_plural': 'Keywords and Links'},
        ),
        migrations.AlterModelOptions(
            name='text_keyword',
            options={'verbose_name': 'keyword and intent', 'verbose_name_plural': 'Keywords and Intents'},
        ),
    ]
