# Generated by Django 3.1.7 on 2021-03-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210312_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual_response',
            name='new_keyword',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Non-Database Keyword'),
        ),
    ]
