# Generated by Django 3.1.7 on 2021-03-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210312_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='AskConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('file_number', models.CharField(max_length=10, verbose_name='File Number')),
                ('inquiry', models.TextField(verbose_name='Inquiry')),
            ],
            options={
                'verbose_name': 'inquiry',
                'verbose_name_plural': 'Inquiries',
            },
        ),
    ]
