# Generated by Django 3.1.7 on 2021-03-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_askconsultant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askconsultant',
            name='id',
        ),
        migrations.AlterField(
            model_name='askconsultant',
            name='file_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='File Number'),
        ),
    ]
