# Generated by Django 3.1.7 on 2021-03-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210322_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='id',
        ),
        migrations.AlterField(
            model_name='about_us',
            name='about_us_paragraph',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manual_response',
            name='email_id',
            field=models.EmailField(default='', max_length=254, verbose_name='Added By'),
        ),
    ]
