# Generated by Django 3.1.7 on 2021-03-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210323_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us_arabic',
            fields=[
                ('about_us_paragraph_arabic', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'about us',
                'verbose_name_plural': 'About Us (Arabic)',
            },
        ),
        migrations.CreateModel(
            name='AskConsultant_arabic',
            fields=[
                ('name_arabic', models.CharField(max_length=100, verbose_name='Name')),
                ('file_number_arabic', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='File Number')),
                ('inquiry_arabic', models.TextField(verbose_name='Inquiry')),
            ],
            options={
                'verbose_name': 'inquiry in arabic',
                'verbose_name_plural': 'Inquiries in arabic',
            },
        ),
        migrations.CreateModel(
            name='link_keyword_arabic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_values_arabic', models.CharField(help_text='Enter keyword here', max_length=100, verbose_name='Keyword')),
                ('links_arabic', models.CharField(help_text='Enter corresponding link here', max_length=1000, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'arabic keyword and link',
                'verbose_name_plural': 'Arabic Keywords and Links',
            },
        ),
        migrations.CreateModel(
            name='manual_response_arabic',
            fields=[
                ('new_keyword_arabic', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Non-Database Keyword')),
                ('admin_data_arabic', models.TextField(verbose_name='Admin Response')),
                ('email_id_arabic', models.EmailField(default='', max_length=254, verbose_name='Added By')),
            ],
            options={
                'verbose_name': 'arabic manual response',
                'verbose_name_plural': 'Arabic Manual Responses',
            },
        ),
        migrations.CreateModel(
            name='text_keyword_arabic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_value_arabic', models.CharField(help_text='Enter keyword here', max_length=100, verbose_name='Keyword')),
                ('desc_arabic', models.TextField(help_text='Enter corresponding response here', verbose_name='Intent')),
            ],
            options={
                'verbose_name': 'arabic keyword and intent',
                'verbose_name_plural': 'Arabic Keywords and Intents',
            },
        ),
    ]
