# Generated by Django 3.1.7 on 2021-03-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_about_us_arabic_askconsultant_arabic_link_keyword_arabic_manual_response_arabic_text_keyword_arabic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='askconsultant_arabic',
            options={'verbose_name': 'inquiry in arabic', 'verbose_name_plural': 'Inquiries (Arabic)'},
        ),
        migrations.AlterModelOptions(
            name='link_keyword_arabic',
            options={'verbose_name': 'arabic keyword and link', 'verbose_name_plural': 'Keywords and Links (Arabic)'},
        ),
        migrations.AlterModelOptions(
            name='manual_response_arabic',
            options={'verbose_name': 'arabic manual response', 'verbose_name_plural': 'Manual Responses (Arabic)'},
        ),
        migrations.AlterModelOptions(
            name='text_keyword_arabic',
            options={'verbose_name': 'arabic keyword and intent', 'verbose_name_plural': 'Keywords and Intents (Arabic)'},
        ),
    ]
