# Generated by Django 3.1.7 on 2021-03-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20210323_0639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='link_keyword_arabic',
        ),
        migrations.AddField(
            model_name='link_keyword',
            name='keyword_values_arabic',
            field=models.CharField(default='', help_text='Enter keyword in arabic here', max_length=100, verbose_name='Arabic Keyword'),
        ),
    ]
