# Generated by Django 3.1.7 on 2021-03-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210323_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_keyword',
            name='tag',
            field=models.CharField(choices=[('greeting', 'Greeting'), ('goodbye', 'Goodbye'), ('thanks', 'Thanks'), ('noanswer', 'No Answer'), ('options', 'Options')], default='noanswer', help_text='Provide relevant tag here', max_length=10),
        ),
    ]
