# Generated by Django 3.1.7 on 2021-04-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210330_0655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='manual_response_manager',
        ),
    ]
